<?php 
$resultsUserTypes=$this->resultsUserTypes;

$offsetT=$_COOKIE["timezone"];
//echo "<pre>";print_r($resultsUserTypes);die;
?>
<script src="/assets/global/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>

  <table class="table table-striped table-bordered table-hover" width="100%">
    <thead>
        <tr>
          <th width="5%" align="center">S.No.</th>
          <th width="10%" align="center"> Email</th>
          <th width="12%" align="center"> Order Number</th>
          <th width="12%" align="center"> Order Date</th>
          <th width="15%" >Option</th>
          <!--<th width="17%" style="text-align: center"></th>-->
</tr>
    </thead>
    <tbody>
        <?php
        if(!empty($resultsUserTypes)){
        $icount=1;
            foreach ($resultsUserTypes as $key => $val):
               // echo '<pre>'; print_r($val);
             ?> 
                <tr>
                    <td ><?php echo $icount; ?></td>
                    <td><?php echo $val['email']; ?></td>
                    <td><?php echo $val['orderNo']; ?></td>
                    <td><?php echo date("d/m/Y H:i",($val['createdOn']-($offsetT*60))); ?></td>
                    <td><a href="/order/images-details/<?php echo base64_encode($val['id']); ?>/<?php echo base64_encode($val['orderId']); ?>">View Order</a> <?php if(!empty($val['inmate_id'])) {?><a href="/order/inmates-details/<?php echo base64_encode($val['inmate_id']); ?>">/View Inmate</a><?php }?></td>
                    <!--<td><a href="">Delete</a></td>-->
                </tr>
            <?php 
            $icount++;
            endforeach;
        } else { ?>
            <tr>
                <td colspan="10">No record found</td>
            </tr>
        <?php } ?>
    </tbody>
  </table>
		
