<?php $userImages = $this->userImages;
$s3Url = $this->s3Url;
?>


<table class="table table-striped table-bordered table-hover" width="100%">
    <thead>
        <tr>
            <th width="10%" >S.No.</th>
            <th width="30%" >Image</th>
            <th width="30%" >Download</th>
        </tr>
    </thead>
    <tbody>
        <?php
        if(!empty($userImages)){
        $icount=1;
            foreach ($userImages as $key => $val):
//                echo "<pre>";print_r($val);die;
             ?> 
                <tr>
                 <td ><?php echo $icount; ?></td>
                 <td align="center">
                     <div data-imagezoom="true" data-magnification="5"
                             style="width:100px; height:100px; padding:0;  background: url('<?php echo $s3Url.$val['fileUrl'];?>') no-repeat; background-size: 100% 100%;">

                        </div>
                     <!--<img id="myImg_<?php // echo $key ?>" src="<?php // echo $s3Url.$val['fileUrl'];?>" style="width:30%;">-->
                 </td>
                 <td><a href="javascript:;" onclick="window.open('/order/download?file=<?php echo $val['fileUrl'];?>', 'download', 'status=0');">Click to download</a></td>
                </tr>
            <?php 
            $icount++;
            endforeach;
        } else { ?>
            <tr>
                <td colspan="10">No record found</td>
            </tr>
        <?php } ?>
    </tbody>
  </table>


<!--<script src="../js/jquery.min.js" type="text/javascript"></script>-->  
    <script src='jquery-1.8.3.min.js'></script>
<script src="/js/bootstrap.min.js" type="text/javascript"></script>
<script src="/js/imagezoom.js" type="text/javascript"></script>
<!--<script src='/js/jquery.elevatezoom.js' type="text/javascript"></script>-->

<!--<script>
    var userImages = '<?php // echo json_encode($userImages) ?>';
    userImages = $.parseJSON(userImages);
    $.each(userImages,function(i){
//        var minHeight = $('#myImg_'+i).prop('naturalHeight');
        
//        minHeight = minHeight / 4;
//        console.log(minHeight);
        $('#myImg_'+i).elevateZoom({
            zoomType: "window",
            cursor: "crosshair",
            zoomWindowFadeIn: 500,
            zoomWindowFadeOut: 750,
            zoomWindowWidth:400,
            zoomWindowHeight:400
        }); 
    });
    </script>-->