<?php $userInmates = $this->userInmates;
?>


<table class="table table-striped table-bordered table-hover" width="100%">
    <thead>
        <tr>

            <th width="30%" >Inmate</th>
            <th width="30%" >Details</th>
        </tr>
    </thead>
    <tbody>
        <?php
        if(!empty($userInmates)){
//        $icount=1;
            foreach ($userInmates as $key => $val):

             ?> 
                <tr>

                 <td align="center"><?php echo $val['inmates_name'] ;?></td>
                 <td align="center"><?php echo $val['inmates_detail'] ; ?></td>
                </tr>
            <?php 
//            $icount++;
            endforeach;
        } else { ?>
            <tr>
                <td colspan="10">No record found</td>
            </tr>
        <?php } ?>
    </tbody>
  </table>


<!--<script src="../js/jquery.min.js" type="text/javascript"></script>-->  
    <script src='jquery-1.8.3.min.js'></script>
<script src="/js/bootstrap.min.js" type="text/javascript"></script>
<script src="/js/imagezoom.js" type="text/javascript"></script>
<!--<script src='/js/jquery.elevatezoom.js' type="text/javascript"></script>-->

<!--<script>
    var userImages = '<?php // echo json_encode($userImages) ?>';
    userImages = $.parseJSON(userImages);
    $.each(userImages,function(i){
//        var minHeight = $('#myImg_'+i).prop('naturalHeight');
        
//        minHeight = minHeight / 4;
//        console.log(minHeight);
        $('#myImg_'+i).elevateZoom({
            zoomType: "window",
            cursor: "crosshair",
            zoomWindowFadeIn: 500,
            zoomWindowFadeOut: 750,
            zoomWindowWidth:400,
            zoomWindowHeight:400
        }); 
    });
    </script>-->