<?php echo $this->doctype(); ?>

<html lang="en">
    <head>

        <meta charset="utf-8">
        <?php echo $this->headTitle('PrizPix '. $this->translate('Admin Panel'))->setSeparator(' - ')->setAutoEscape(false) ?>
          <link href="/img/favicon.ico" rel="shortcut icon" type="image/vnd.microsoft.icon">
        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink()
                        ->prependStylesheet($this->basePath('assets/admin/layout/css/custom.css'))
                        ->prependStylesheet($this->basePath('assets/admin/layout/css/themes/default.css'))
                        ->prependStylesheet($this->basePath('assets/admin/layout/css/layout.css'))
                        ->prependStylesheet($this->basePath('assets/global/css/plugins.css'))
                        ->prependStylesheet($this->basePath('assets/global/css/components.css'))
                        ->prependStylesheet($this->basePath('assets/admin/pages/css/tasks.css'))
                        ->prependStylesheet($this->basePath('assets/global/plugins/jqvmap/jqvmap/jqvmap.css'))
                        ->prependStylesheet($this->basePath('assets/global/plugins/fullcalendar/fullcalendar/fullcalendar.css'))
                        ->prependStylesheet($this->basePath('assets/global/plugins/bootstrap-daterangepicker/daterangepicker-bs3.css'))
                        ->prependStylesheet($this->basePath('assets/global/plugins/gritter/css/jquery.gritter.css'))
                        ->prependStylesheet($this->basePath('assets/global/plugins/bootstrap-switch/css/bootstrap-switch.min.css'))
                        ->prependStylesheet($this->basePath('assets/global/plugins/select2/select2.css'))
                        ->prependStylesheet($this->basePath('assets/global/plugins/uniform/css/uniform.default.css'))
                        ->prependStylesheet($this->basePath('assets/global/plugins/bootstrap/css/bootstrap.min.css'))
                        ->prependStylesheet($this->basePath('assets/global/plugins/simple-line-icons/simple-line-icons.min.css'))
                        ->prependStylesheet($this->basePath('assets/global/plugins/font-awesome/css/font-awesome.min.css'))
                        ->prependStylesheet('https://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all') ?>
    
        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

<script src="/js/customLib.js" type="text/javascript"></script>
        <script>
            var d = new Date();
            var timezone = d.getTimezoneOffset();
            document.cookie="timezone"+"=" + timezone;
        </script>
    </head>
    <body class="page-header-fixed page-quick-sidebar-over-content">
        <!-- BEGIN HEADER -->
<div class="page-header navbar navbar-fixed-top">
	<!-- BEGIN HEADER INNER -->
	<div class="page-header-inner">
		<!-- BEGIN LOGO -->
                <div class="page-logo" style="padding-left: 0px;">
			<a href="/">
                            <!--<h2 style="color:whitesmoke">Admin</h2>-->
                            <!--<a href="#" class="slogo"> <img src="/img/logo1.png" alt="" style="width:234px; height: 46px;"></a>-->
			</a>
			<div class="menu-toggler sidebar-toggler hide">
				<!-- DOC: Remove the above "hide" to enable the sidebar toggler button on header -->
			</div>
		</div>
		<!-- END LOGO -->
		<!-- BEGIN RESPONSIVE MENU TOGGLER -->
		<a href="javascript:;" class="menu-toggler responsive-toggler" data-toggle="collapse" data-target=".navbar-collapse">
		</a>
		<!-- END RESPONSIVE MENU TOGGLER -->
		<!-- BEGIN TOP NAVIGATION MENU -->
		<div class="top-menu">
			<?php echo $this->partial("layout/common/header.phtml");?>
		</div>
		<!-- END TOP NAVIGATION MENU -->
	</div>
	<!-- END HEADER INNER -->
</div>
<!-- END HEADER -->
<div class="clearfix">
</div>
        <div class="page-container">
        <?php echo $this->partial("layout/common/side-menu.phtml");?>
        <div class="page-content-wrapper">
        <div class="page-content">
        <?php echo  $this->partial("flash/message"); ?>
            <?php echo $this->content; ?>  
            </div>          
        </div>
        </div> <!-- /container -->
        <div class="page-footer">
	<div class="page-footer-inner">
		 2017 &copy; PrizPix
	</div>
	<div class="scroll-to-top">
		<i class="icon-arrow-up"></i>
	</div>
</div>
        
        <!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->
<!-- BEGIN CORE PLUGINS -->
<!--[if lt IE 9]>
<script src="/assets/global/plugins/respond.min.js"></script>
<script src="/assets/global/plugins/excanvas.min.js"></script> 
<![endif]-->
<script src="/assets/global/plugins/jquery-1.11.0.min.js" type="text/javascript"></script>
<script src="/assets/global/plugins/jquery-migrate-1.2.1.min.js" type="text/javascript"></script>
<!-- IMPORTANT! Load jquery-ui-1.10.3.custom.min.js before bootstrap.min.js to fix bootstrap tooltip conflict with jquery ui tooltip -->
<script src="/assets/global/plugins/jquery-ui/jquery-ui-1.10.3.custom.min.js" type="text/javascript"></script>
<script src="/assets/global/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
<script src="/assets/global/plugins/bootstrap-hover-dropdown/bootstrap-hover-dropdown.min.js" type="text/javascript"></script>
<script src="/assets/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script>
<script src="/assets/global/plugins/jquery.blockui.min.js" type="text/javascript"></script>
<script src="/assets/global/plugins/jquery.cokie.min.js" type="text/javascript"></script>
<script src="/assets/global/plugins/uniform/jquery.uniform.min.js" type="text/javascript"></script>
<script src="/assets/global/plugins/bootstrap-switch/js/bootstrap-switch.min.js" type="text/javascript"></script>
<!-- END CORE PLUGINS -->
<script src="/assets/global/plugins/jquery-mixitup/jquery.mixitup.min.js" type="text/javascript"></script>
<script src="/assets/global/plugins/fancybox/source/jquery.fancybox.pack.js" type="text/javascript"></script>
<!-- BEGIN PAGE LEVEL PLUGINS -->
<script src="/assets/global/plugins/flot/jquery.flot.min.js" type="text/javascript"></script>
<script src="/assets/global/plugins/flot/jquery.flot.resize.min.js" type="text/javascript"></script>
<script src="/assets/global/plugins/jquery.pulsate.min.js" type="text/javascript"></script>
<!-- IMPORTANT! fullcalendar depends on jquery-ui-1.10.3.custom.min.js for drag & drop support -->
<!-- END PAGE LEVEL PLUGINS -->
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script type="text/javascript" src="/assets/global/plugins/select2/select2.min.js"></script>

<!-- <script src="/assets/admin/pages/scripts/portfolio.js"></script> -->
<script src="/assets/global/scripts/metronic.js" type="text/javascript"></script>
<script src="/assets/admin/layout/scripts/layout.js" type="text/javascript"></script>
<script src="/assets/admin/layout/scripts/quick-sidebar.js" type="text/javascript"></script>
<script src="/assets/admin/layout/scripts/demo.js" type="text/javascript"></script>
<!-- <script src="/assets/admin/pages/scripts/index.js" type="text/javascript"></script> -->
<script src="/assets/admin/pages/scripts/tasks.js" type="text/javascript"></script>
<script type="text/javascript" src="/ajaxloader/jquery.ajaxloader.js"></script>
<?php echo $this->inlineScript() ?>
<!-- END PAGE LEVEL SCRIPTS -->
<script>
jQuery(document).ready(function() {
	 ajaxLoader.init({
         'loader': 'dots',
         'theme' : 'dark',
         'size' : 10,
         'noloadingURL' : ['/application/index/search','/users/get-notifications'],
         });
   Metronic.init(); // init metronic core componets
   Layout.init(); // init layout
//    QuickSidebar.init(); // init quick sidebar
   Demo.init(); 
});
</script>
    </body>
</html>
