
<table class="table table-striped table-bordered table-hover" width="100%">
<input type="hidden" name="planId" id="noteId" value="<?php echo $this->planId;?>"/>
<tbody>
<tr data-index="0">
<td colspan="7">
<div class="card-view">
<span class="title" style=""><b>Plan Name :-</b></span>&emsp;&emsp;
<span class="value"><?php echo $this->planDetails[0]['planName']; ?></span>
</div>
<div class="card-view">
<span class="title" style=""><b>No of images :-</b></span>&emsp;
<span class="value"><?php echo $this->planDetails[0]['quantity']; ?></span>
</div>
<div class="card-view">
<span class="title" style=""><b>Price :-</b></span>&emsp;&emsp;&emsp;&emsp;&emsp;
<span class="value"><?php echo $this->planDetails[0]['price']; ?></span>
</div>
<div class="card-view">
<span class="title" style=""><b>Currency :-</b></span>&emsp;&emsp;&emsp;
<span class="value"><?php echo $this->planDetails[0]['currency']; ?></span>
</div>
</td>
</tr>
</tbody>
</table>