<?php 
$resultsUserTypes=$this->resultsUserTypes;
//echo "<pre>";print_r($resultsUserTypes);die;
?>
<script src="/assets/global/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>

  <table class="table table-striped table-bordered table-hover" width="100%">
    <thead>
        <tr>
          <th width="5%" align="center">S.No.</th>
          <th width="10%" align="center">Name</th>
          <th width="10%" align="center">Email</th>
          <th width="12%" align="center">Transaction Id</th>
          <th width="12%" align="center">Amount</th>
          <th width="12%" align="center">Plan Name</th>
          <th width="12%" align="center">Payment Date</th>
          <th width="10%" align="center">Option</th>
</tr>
    </thead>
    <tbody>
        <?php
        if(!empty($resultsUserTypes)){
        $icount=1;
            foreach ($resultsUserTypes as $key => $val):
             ?> 
                <tr>
                    <td ><?php echo $icount; ?></td>
                    <td><?php echo $val['firstName'].' '.$val['lastName']; ?></td>
                    <td><?php echo $val['email']; ?></td>
                    <td><?php echo $val['transactionId']; ?></td>
                    <td><?php echo $val['amount']; ?></td>
                    <td><a href="javascript:;" onclick="planDetails(<?php echo $val['planId']; ?>)"><?php echo $val['planName']; ?></a></td>
                    <td><?php echo date("d/m/Y H:i",$val['createdOn']); ?></td>
                    <td><a href="javascript:;" onclick="blockTransactionDetails(<?php echo $val['orderId']; ?>,'delete')">Delete </a></td>
                    
                </tr>
            <?php 
            $icount++;
            endforeach;
        } else { ?>
            <tr>
                <td colspan="10">No record found</td>
            </tr>
        <?php } ?>
    </tbody>
  </table>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel" style="margin-left:14px;"><b>Plan Details</b></h4>
     
      <div class="modal-body">
       
      </div>
         </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default do" data-dismiss="modal">Close</button>
        
       
      </div>
    </div>
  </div>
</div>






<script>
   
    
    
    </script>