<link rel="stylesheet" type="text/css" href="/assets/global/plugins/bootstrap-fileinput/bootstrap-fileinput.css"/>
<link id="style_color" type="text/css" rel="stylesheet" href="/assets/admin/layout/css/themes/default.css">
<link type="text/css" rel="stylesheet" href="/assets/admin/layout/css/custom.css">
<script src="/assets/global/plugins/bootstrap-fileinput/bootstrap-fileinput.js" type="text/javascript"></script>
<div class="form-group">
                    <label class="col-md-2 control-label" for="logo">Logo<span class="required"> * </span></label>
                        <div class="col-md-4 ">
                        <div class="fileinput fileinput-new" data-provides="fileinput">
							<div class="fileinput-new thumbnail" style="width: 200px; height: 150px;">
								<img src="http://www.placehold.it/200x150/EFEFEF/AAAAAA&amp;text=no+image" alt=""/>
							</div>
						<div id="offerBanner_thumbnail" class="fileinput-preview fileinput-exists thumbnail" style="max-width: 200px; max-height: 150px;">
						</div>
						<div>
								<span class="btn default btn-file">
								<span class="fileinput-new">
								Select image </span>
								<span class="fileinput-exists">
								Change </span>
								<input type="file" name="logo" id="logo">
								<input	id="image_file_upload" type="hidden" value="" name="offerPic"> 
								</span>
								<a href="#" id="rmv" class="btn red fileinput-exists" data-dismiss="fileinput">
								Remove </a>
							</div>
						</div>
                       
                    </div>
                 </div> 
<?php
    echo $this->inlinescript()
            ->appendFile($this->basepath() . '/assets/global/plugins/jquery-file-upload/js/jquery.fileupload.js')
    ?>
<script>
//$(function(){
//	$('#logo').fileupload({
//        maxNumberOfFiles: 1,
////         maxFileSize: 1024,
////         imageMaxWidth: 100,
////         imageMaxHeight: 100,
//        acceptFileTypes: /(\.|\/)(gif|jpe?g|png)$/i,
//        url: '/application/index/image-upload',
//        sequentialUploads: true,
//        done: function (e, data) {
//            if(data.jqXHR.responseJSON.error == '1'){
//                alert('Please upload image with 100 * 100');
//                $('#rmv').hide();
//            }
//            $("#offerBanner_thumbnail").html("<img  src='" + data.jqXHR.responseJSON.url + "'/>");
//            $("#logo").next("#image_file_upload").val(data.jqXHR.responseJSON.realImage);
//
//        }
//    });
//});
//</script>