<?php 
$resultsUserTypes=$this->resultsUserTypes;
//echo "<pre>";print_r($resultsUserTypes);die;
?>
<script src="/assets/global/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>

  <table class="table table-striped table-bordered table-hover" width="100%">
    <thead>
        <tr>
           
            <th width="3%" >S.No.</th>
            <th width="9%" >Name</th>
            <th width="10%"> Email</th>
            <th width="10%"> Address1</th>
            <th width="10%"> Address2</th>
            <th width="10%"> City</th>
            <th width="10%"> State</th>
            <th width="11%"> Postal Code</th>
            <th width="10%"> Country</th>
            <th width="10%"> Details</th>
        </tr>
    </thead>
    <tbody>
        <?php
        if(!empty($resultsUserTypes)){
        $icount=1;
            foreach ($resultsUserTypes as $key => $val):
//                echo "<pre>";print_r($val);die;
             ?> 
                <tr>
                 <td ><?php echo $icount; ?></td>
                    <td><?php echo $val['firstName'].' '.$val['lastName']; ?></td>
                    <td><?php echo $val['email']; ?></td>
                    <td><?php echo $val['primaryAddress']; ?></td>
                    <td><?php echo $val['secondaryAddress']; ?></td>
                    <td><?php echo $val['city']; ?></td>
                    <td><?php echo $val['state']; ?></td>
                    <td><?php echo $val['postalCode']; ?></td>
                    <td><?php echo $val['country']; ?></td>
                    <td><a href="/users/user-more-details/<?php echo base64_encode($val['id']);?>">More Details</a></td>
                </tr>
            <?php 
            $icount++;
            endforeach;
        } else { ?>
            <tr>
                <td colspan="10">No record found</td>
            </tr>
        <?php } ?>
    </tbody>
  </table>
		
