<?php 
$resultsUserTypes=$this->resultsUserTypes;
//echo "<pre>";print_r($resultsUserTypes);die;
?>
<script src="/assets/global/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>

<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <i class="icon-user"></i>
            <a href="/users/index">User Management</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
      Users Listing
        </li>
    </ul>
</div>
<!-- END PAGE HEADER-->
<!-- BEGIN PAGE CONTENT-->
<input type="hidden" id="moduleId" value="users">
<div class="row" >
    <div class="portlet box yellow-casablanca">
        <div class="portlet-title">
            <div style="position: relative; float: left; " class="col-md-10 tools">
            <label class="col-md-4">
                    <!--<input id="searchText" type="text" placeholder="Eg: email, mobile.." class="form-control input-circle">-->
                </label>
                <label class="col-md-3 content-label">
                    <?php //echo '<pre>'; print_r($this->state); die;?>
                    <!--<select class="form-control select2" id="stateId">-->
                        <?php // foreach ($this->state as $key => $val) { ?>
                            <!--<option value="<?php // echo $key; ?>"><?php // echo ucfirst($val); ?></option>-->
                        <?php // } ?>
                    </select>
                </label>
                <!--<label class="col-md-3 content-label">-->
                    <!--<select class="form-control select2" id="userTypes">-->
                        <?php // foreach ($this->userTypes as $key => $val) { ?>
                            <option value="<?php // echo $key; ?>"><?php // echo ucfirst($val); ?></option>
                        <?php // } ?>
                    </select>
                </label>
                
                <!--<button type="button" style="vertical-align: top" class="btn btn-primary" onclick="myEzo.getExcutiveList('search');">Search</button>-->
            </div>
<!--            <div class="tools" style="float: right;">
                <label class="content-label">
                    <a class="btn btn-primary" href="/users/add-user" title="Add New User">Add New User</a> </label>
            </div>-->
            
            
        </div>

        <div class="portlet-body">
            <div class="table-responsive" id="resultData">
                <input type="hidden" id="currentPage" value="1">
                <input type="hidden" name="columnName" id="columnName" value="userId" />
				<input type="hidden" name="sortBy" id="sortBy" value="desc" /> 
            </div>
            <div id="getlist">
                
            </div>
            
        </div>
    </div>

</div>
<!--<div class="modal fade" id="fosModal" tabindex="-1" role="basic" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"></button>
                <h4 class="modal-title"></h4>
            </div>
            <div class="modal-body">-->
               
                
                
                
<!--            </div>-->
            

<div class="popup eventPopup modal fade" id="uploadScreen" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h1 class="modal-title text-center blackColor">Upload</h1>
            </div>
            <div class="modal-body">
              
            </div>
        </div>
    </div>
</div>


            
            
<!--            <div class="modal-footer">
                <button type="button" class="btn default" data-dismiss="modal">Close</button>
            </div>-->
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<script type="text/javascript">
$(function(){
    getData('0');
	   });
        function getData(seeAllFlag){
            var data = {};
            data['seeAllFlag'] = seeAllFlag;
           $.ajax({
                url: '/users/get-user-list',
                type: 'POST',
                datatype: 'HTML', //server return data in the provided formate
                data: data,
                success: function (data) {
                    $("#getlist").html(data);
                    }
            });  
        }
        
        
        
        function blockUser(userId,statusType) {
   if (confirm('Do you want to ' + statusType + ' this user?')) {
     var data = {}; //empty array
        data['userId'] = userId;
        data['statusType'] = statusType;
         $.ajax({
                url: '/users/block-user',
                type: 'POST',
                datatype: 'json', //server return data in the provided formate
                data: data,
                success: function (data) {
                    getData();
                    }
            });
   }
   }
        
        
        
 
</script>		
