<?php
$userDetails=$this->userDetails;
$userPlanDetails=$this->userPlanDetails;
//echo "<pre>";print_r($userDetails);die;
?>


<!--Billing Details -->

<div class="portlet box yellow-casablanca">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-cogs"></i>
            Billing Details
        </div>
        <div class="actions">
            <!--<a class="btn btn-default btn-sm" href="javascript:;">
            <i class="fa fa-pencil"></i>
            Edit
            </a>-->
        </div>
    </div>

    <div class="portlet-body">
        <div class="row static-info">
            <div class="col-md-12 value">
                <table class="table table-striped table-bordered table-hover" width="100%">
                    <thead>
                    <tr>
                        <th width="10%">Billing Label</th>
                        <th width="14%">Billing Primary Address</th>
                        <th width="16%">Billing Secondary Address</th>
                        <th width="8%">Billing City</th>
                        <th width="8%">Billing State</th>
                        <th width="12%">Billing Postal Code</th>
                        <th width="10%">Billing Country</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php
                    if(!empty($userDetails)){
//        $icount=1;
//                echo "<pre>";print_r($val);die;
                        ?>
                        <tr>

                            <td><?php echo $userDetails[0]['billingAddressLabel']; ?></td>
                            <td><?php echo $userDetails[0]['billingAddressPrimary']; ?></td>
                            <td><?php echo $userDetails[0]['billingAddressScondary']; ?></td>
                            <td><?php echo $userDetails[0]['billingCity']; ?></td>
                            <td><?php echo $userDetails[0]['billingState']; ?></td>
                            <td><?php echo $userDetails[0]['billingPostalCode']; ?></td>
                            <td><?php echo $userDetails[0]['billingCountry']; ?></td>

                        </tr>
                    <?php } else { ?>
                        <tr>
                            <td colspan="10">No record found</td>
                        </tr>
                    <?php } ?>
                    </tbody>
                </table>

            </div>
        </div>
    </div>
</div>


<!-- Recovery & Security Details   -->

<div class="portlet box yellow-casablanca">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-cogs"></i>
            Recovery & Security Details
        </div>
        <div class="actions">
            <!--<a class="btn btn-default btn-sm" href="javascript:;">
            <i class="fa fa-pencil"></i>
            Edit
            </a>-->
        </div>
    </div>

    <div class="portlet-body">
        <div class="row static-info">
            <div class="col-md-12 value">
                <table class="table table-striped table-bordered table-hover" width="100%">
                    <thead>
                    <tr>
                        <th width="8%">Security Pin</th>
                        <th width="9%">Transaction Pin</th>
                        <th width="10%">Security Email</th>
                        <th width="12%">Security Question 1</th>
                        <th width="8%">Answer 1</th>
                        <th width="13%">Security Question 2</th>
                        <th width="10%">Answer 2</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php
                    if(!empty($userDetails)){
//        $icount=1;
//                echo "<pre>";print_r($val);die;
                        ?>
                        <tr>

                            <td><?php echo $userDetails[0]['securityPin']; ?></td>
                            <td><?php echo $userDetails[0]['transactionPin']=='0' ? 'Off' : 'On'; ?></td>
                            <td><?php echo $userDetails[0]['secondaryEmail']; ?></td>
                            <td><?php echo $userDetails[0]['securityQuestion1']; ?></td>
                            <td><?php echo $userDetails[0]['Answer1']; ?></td>
                            <td><?php echo $userDetails[0]['securityQuestion2']; ?></td>
                            <td><?php echo $userDetails[0]['Answer2']; ?></td>

                        </tr>
                    <?php } else { ?>
                        <tr>
                            <td colspan="10">No record found</td>
                        </tr>
                    <?php } ?>
                    </tbody>
                </table>

            </div>
        </div>
    </div>
</div>

<!-- Plan Details   -->

<div class="portlet box yellow-casablanca">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-cogs"></i>
            Plans Details
        </div>
        <div class="actions">

            <h4>Current balance:- <?php echo $this->totalImageCount; ?></h4>
        </div>
    </div>

    <div class="portlet-body">
        <div class="row static-info">
            <div class="col-md-12 value">
                <table class="table table-striped table-bordered table-hover" width="100%">
                    <thead>
                    <tr>
                        <th width="12%">Plan Name</th>
                        <th width="12%">No of images</th>
                        <th width="12%">Price</th>
                        <th width="12%">Currency</th>
                        <th width="12%">Purchase Date</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php
                    if(!empty($userPlanDetails)){
                        foreach ($userPlanDetails as $key => $val):
                            ?>
                            <tr>

                                <td><?php echo $val['planName']; ?></td>
                                <td><?php echo $val['quantity']; ?></td>
                                <td><?php echo $val['price']; ?></td>
                                <td><?php echo $val['currency']; ?></td>
                                <td><?php echo date('d/m/Y H:i',$val['createdOn']); ?></td>

                            </tr>
                            <?php
                        endforeach;
                    } else { ?>
                        <tr>
                            <td colspan="5">No record found</td>
                        </tr>
                    <?php } ?>
                    </tbody>
                </table>

            </div>
        </div>
    </div>
</div>

