<?php 
$userDetails=$this->userDetails;
$userPlanDetails=$this->userPlanDetails;
$offsetT=$_COOKIE["timezone"];
//echo "<pre>";print_r($userDetails);die;
?>


<!--Billing Details -->




<!-- Recovery & Security Details   -->



<!-- Plan Details   -->

<div class="portlet box yellow-casablanca">
<div class="portlet-title">
<div class="caption">
<i class="fa fa-cogs"></i>
Plans Details
</div>
<div class="actions">

    <h4>Current balance:- <?php echo $this->totalImageCount; ?></h4>
</div>
</div>

<div class="portlet-body">
<div class="row static-info">
<div class="col-md-12 value">
    <table class="table table-striped table-bordered table-hover" width="100%">
        <thead>
        <tr>
           <th width="12%">Plan Name</th>
           <th width="12%">No of images</th>
           <th width="12%">Price</th>
           <th width="12%">Currency</th>
           <th width="12%">Purchase Date</th>
        </tr>
    </thead>
    <tbody>
        <?php
        if(!empty($userPlanDetails)){
         foreach ($userPlanDetails as $key => $val):
             ?> 
                <tr>
                
                    <td><?php echo $val['planName']; ?></td>
                    <td><?php echo $val['quantity']; ?></td>
                    <td><?php echo $val['price']; ?></td>
                    <td><?php echo $val['currency']; ?></td>
                    <td><?php echo date('d/m/Y H:i',($val['createdOn']-($offsetT*60))); ?></td>
                   
                </tr>
         <?php
            endforeach;
        } else { ?>   
            <tr>
                <td colspan="5">No record found</td>
            </tr>
          <?php } ?>   
    </tbody>
    </table>

</div>
</div>
</div>
</div>

