<?php 
$getNotes=$this->getNotes;
//echo "<pre>";print_r($getPlan);die;
?>
<script src="/assets/global/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>

  <table class="table table-striped table-bordered table-hover" width="100%">
    <thead>
        <tr>
          <th width="5%">S.No.</th>
          <th width="10%">Note Description</th>
          <!--<th width="15%">Option</th>-->
</tr>
    </thead>
    <tbody>
        <?php
        if(!empty($getNotes)){
        $icount=1;
            foreach ($getNotes as $key => $val):
             ?> 
                <tr>
                    <td ><?php echo $icount; ?></td>
                    <td class="blackColor" ><a href="javascript:;" onclick="noteDescription(<?php echo $val['noteId'];?>)" ><?php echo $this->escapeHtml(strlen($val['noteDescription']) > 20 ? substr($val['noteDescription'], 0, 50) . "............." : $val['noteDescription']); ?></a></td>
                    
                </tr>
            <?php 
            $icount++;
            endforeach;
        } else { ?>
            <tr>
                <td colspan="10">No record found</td>
            </tr>
        <?php } ?>
    </tbody>
  </table>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel" style="margin-left:14px;"><b>Notes Description</b></h4>
     
      <div class="modal-body">
       
      </div>
         </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default do" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary edit" onclick="editNoteForm()">Edit</button>
        <button type="button" class="btn btn-primary delete"onclick="deleteNote('delete')">Delete</button>
       
      </div>
    </div>
  </div>
</div>
		
<script>
     function noteDescription(noteId){
         var data= {};
           data['noteId'] = noteId;
          $.ajax({
                url: '/notes/get-notes-description',
                type: 'POST',
                datatype: 'HTML', //server return data in the provided formate
                data: data,
                success: function (data) {
                    $("#myModal").modal('show');
                    $(".modal-body").html(data);
                    
                }  
            });  
     }
       
        function  editNoteForm(){
            var data ={};
             data['noteId']=  $('#noteId').val();
                $.ajax({
                url: '/notes/edit-note/'+btoa(data['noteId']),
                type: 'GET',
                datatype: 'HTML', //server return data in the provided formate
                success: function (data) {
                     $("#myModal").modal('show');
                     $(".do").hide();
                     $(".edit").hide();
                     $(".delete").hide();
                     $(".modal-body").html(data);
                    }
            });  
    }
    
    function deleteNote(statusType){
         if (confirm('Do you want to ' + statusType + ' this note?')) {
            var data ={};
             data['noteId']=  $('#noteId').val();
                $.ajax({
                url: '/notes/delete-note',
                type: 'POST',
                datatype: 'HTML', //server return data in the provided formate
                data: data,
                success: function (data) {
                    window.location.href= '/notes/index';
                    }
            });  
        }
    }
    
    
    </script>