<link id="style_color" type="text/css" rel="stylesheet" href="/assets/admin/layout/css/themes/default.css">
<link type="text/css" rel="stylesheet" href="/assets/admin/layout/css/custom.css">
<link href="/assets/global/plugins/bootstrap-datepicker/css/datepicker.css" type="text/css" rel="stylesheet">
<style>
    .error{
        color: red;
    }
</style>
<div class="row ">
    <!-- BEGIN SAMPLE FORM PORTLET-->
    <div class="portlet box yellow-casablanca">
        <div class="portlet-title">
            <div class="caption">
                <i class="fa fa-reorder"></i> Add Plan
            </div>
        </div>
        <div class="portlet-body form">
            <?php
            $form = $this->form;
            $form->setAttribute('action', '');
            $form->prepare();
            echo $this->form()->openTag($form);
            ?>

            <div class="form-body">
<!--                <div class="form-group">

                    <label class="col-md-2 control-label" for="fosFirstName">Duration<span class="required"> * </span></label>

                    <div class="col-md-2">
                        One Time
                        <input type="radio" name="duration" value="0" onclick="durationDetails(this.value)">
                    </div>
                    <div class="col-md-2">
                        Recurring
                        <input type="radio" name="duration" value="1" onclick="durationDetails(this.value)">
                    </div>

                </div>-->

<!--                <div id="oneTime" style="display: none">
                    <div class="form-group">
                        <label class="col-md-2 control-label" for="fosLastName">Start date<span class="required"> * </span></label>
                        <div class="col-md-4 ">
                            <?php // echo $this->formElement($form->get('startDate')); ?>
                            <span class="help-block">
                                <?php // echo $this->formElementErrors($form->get('startDate')); ?>
                            </span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-2 control-label" for="fosLastName">End date<span class="required"> * </span></label>
                        <div class="col-md-4 ">
                            <?php // echo $this->formElement($form->get('endDate')); ?>
                            <span class="help-block">
                                <?php // echo $this->formElementErrors($form->get('endDate')); ?>

                            </span>
                        </div>

                    </div>
                </div>-->
<!--                <div id="recurring" style="display: none">
                    <div class="form-group">
                        <label class="col-md-2 control-label" for="fosLastName"><span class="required">  </span></label>
                        <div class="col-md-2 ">
                            Year
                            <input type="radio" name="recurring" value="year">
                        </div>


                        <div class="col-md-2 ">
                            Month
                            <input type="radio" name="recurring" value="month">
                        </div>
                    </div>


                    <div class="form-group">
                        <label class="col-md-2 control-label" for="fosLastName"><span class="required">  </span></label>
                        <div class="col-md-2 ">
                            Week
                            <input type="radio" name="recurring" value="week">
                        </div>

                        <div class="col-md-2 ">
                            Daily
                            <input type="radio" name="recurring" value="daily">
                        </div>

                    </div>
                </div>-->
                <!--<div id="noOfImages" style="display: none;">-->
                <div class="form-group">
                    <label class="col-md-2 control-label" for="fosLastName" >Plan Name<span class="required"> * </span></label>
                    <div class="col-md-4 ">
                        <?php echo $this->formElement($form->get('planName')); ?>
                        <span class="help-block">
                            <?php echo $this->formElementErrors($form->get('planName')); ?>
                        </span>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-2 control-label" for="fosLastName" >No of images<span class="required"> * </span></label>
                    <div class="col-md-4 ">
                        <?php echo $this->formElement($form->get('noOfImages')); ?>
                        <span class="help-block">
                            <?php echo $this->formElementErrors($form->get('noOfImages')); ?>
                        </span>
                    </div>
                </div>
                <!--</div>-->
                 <!--<div id="price" style="display: none;">-->
                <div class="form-group">
                    <label class="col-md-2 control-label" for="fosLastName">Price<span class="required"> * </span></label>
                    <div class="col-md-4 ">
                        <?php echo $this->formElement($form->get('price')); ?>
                        <span class="help-block">
                            <?php echo $this->formElementErrors($form->get('price')); ?>

                        </span>
                    </div>

                </div>
                 <!--</div>-->
                <div class="form-group">
                    <div class="col-md-4 ">
                        <?php echo $this->formElement($form->get('submit')); ?>

                    </div>
                </div>

            </div>
            <?php echo $this->form()->closeTag($form); ?>

            <?php
            echo $this->inlinescript()
                    ->appendFile($this->basepath() . '/assets/global/plugins/bootstrap-datepicker/js/bootstrap-datepicker.js')
                    ->appendFile($this->basePath() . '/assets/global/plugins/jquery-validation/js/jquery.validate.min.js')
                    ->appendFile($this->basePath() . '/assets/global/plugins/jquery-validation/js/additional-methods.js')
//             ->appendFile($this->basePath() . '/assets/admin/pages/scripts/form-validation.js')
                    ->appendFile($this->basePath() . '/assets/admin/pages/scripts/login.js')
            ?>
            <script>
                $(document).ready(function () {
                    validateAddCandidate();
//                    $('#startDate').datepicker({
//                        format: 'yyyy-mm-dd',
//                        minDate: new Date(),
//                        autoclose: true
//                    });
//                    $('#endDate').datepicker({
//                        format: 'yyyy-mm-dd',
//                        minDate: new Date(),
//                        autoclose: true
//                    });
                });
//                function durationDetails(value) {
//                    if (value == '0') {
//                        $("#oneTime").show();
//                        $("#noOfImages").show();
//                        $("#price").show();
//                        $("#recurring").hide();
//                    } else if (value == '1') {
//                        $("#oneTime").hide();
//                        $("#recurring").show();
//                        $("#noOfImages").show();
//                        $("#price").show();
//                    }
//                }

                function validateAddCandidate() {
                    $('#subcriptionform').validate({// initialize the plugin
                        rules: {
                            noOfImages: {
                                required: true,
                                number: true,
                                min:1
                            },
                            price: {
                                required: true,
                                number: true,
                                min:1
                            },
                            startDate: {
                                required: true,
                              
                            },
                            endDate: {
                                required: true,
                              
                            },
                            planName: {
                                required: true,
                              
                            },
                            expectedSalary: {
                                digits: true
                            }
                        },
                        messages: {
                            noOfImages: {
                                required: '<?php echo $this->translate("Please enter no of images"); ?>',
                                min: '<?php echo $this->translate("Please enter no of images"); ?>'

                            },
                            price: {
                                required: '<?php echo $this->translate("Please enter price"); ?>',
                                min: '<?php echo $this->translate("Please enter price"); ?>'

                            },
                            startDate: {
                                required: '<?php echo $this->translate("Please select start date"); ?>',
                            },
                            endDate: {
                                required: '<?php echo $this->translate("Please select end date"); ?>',
                            },
                            planName: {
                                required: '<?php echo $this->translate("Please enter plan name"); ?>',
                            },
                        }, submitHandler: function (form) {
                            if ($('#subcriptionform').valid()) {
                                 addPlan();
                            }
                        },
                    });
                }
                function  addPlan(){
              var formData=  $('#subcriptionform').serializeArray();
                $.ajax({
                url: '/subscription/add-plan',
                type: 'POST',
                datatype: 'HTML', //server return data in the provided formate
                data: formData,
                success: function (data) {
//                    return false;
                    window.location.href= '/subscription/index';
//                    $("#getlist").html(data);
                    }
            });  
    }
     
            </script>