<?php 
$getPlan=$this->getPlan;
//echo "<pre>";print_r($getPlan);die;
?>
<script src="/assets/global/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>

  <table class="table table-striped table-bordered table-hover" width="100%">
    <thead>
        <tr>
          <th width="5%">S.No.</th>
          <th width="10%">Plan Name</th>
          <th width="15%">No of images</th>
          <th width="15%">Price</th>
          <th width="15%">Option</th>
</tr>
    </thead>
    <tbody>
        <?php
        if(!empty($getPlan)){
        $icount=1;
            foreach ($getPlan as $key => $val):
             ?> 
                <tr>
                    <td ><?php echo $icount; ?></td>
                    <td><?php echo $val['planName']; ?></td>
                    <td><?php echo $val['noOfImages']; ?></td>
                    <td><?php echo $val['price']; ?></td>
                    <td> <a href=""  onclick="deletePlan(<?php echo $val['planId']; ?>,'delete')">Delete</a></td>
<!--                    <a href="/subscription/edit-plan/--><?php //echo base64_encode($val['planId']); ?><!--" >Edit</a> /-->
                </tr>
            <?php 
            $icount++;
            endforeach;
        } else { ?>
            <tr>
                <td colspan="10">No record found</td>
            </tr>
        <?php } ?>
    </tbody>
  </table>
		
<script>
     
       
        
    
    </script>